source "https://rubygems.org"

# Jekyll 4 — требуется для just-the-docs
gem "jekyll", "~> 4.3"

# just-the-docs как gem (не remote_theme)
gem "just-the-docs", "~> 0.10"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
end
